[package]
name = "veritas"
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/hessiser/veritas/"

[package.metadata]
region = "global"
is_beta = true
patch = "3.2.3"
hotfix = "0.4"

[lib]
crate-type = ["cdylib"]

[dependencies]
retour = { version = "0.3", features = ["static-detour"] }
ctor = "0.4.1"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
anyhow = "1.0.97"
log = "0.4"
egui = "0.31.1"
egui_plot = "0.32.1"
edio11 = { git = "https://github.com/hessiser/edio11-rs.git", rev = "8127440" }

egui_logger = "0.6.3"
function_name = "0.3.0"
slog = "2.7.0"
slog-term = "2.9.1"

[dependencies.windows]
version = "0.60.0"
features = [
    "Win32_Foundation",
    "Win32_System_LibraryLoader",
    "Win32_System_Console",
    "Win32_Security",
    "Win32_System_Threading",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_Graphics_Direct3D",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Direct3D11"
]

[build-dependencies]
cargo_metadata = "0.19.2"
regex = "1.11.1"
toml_edit = "0.22.25"
