name: Bug report
description: Create a report to help us improve
title: "[BUG]: "
labels:
  - bug

body:
  - type: markdown
    attributes:
      value: |
        Please attach `veritas.debug.log`.
        Do NOT restart the game before collecting logs.

  - type: input
    id: plugin_version
    attributes:
      label: Plugin version
      placeholder: 0.2.32
    validations:
      required: true

  - type: input
    id: game_version
    attributes:
      label: Game version
      placeholder: 4.1.0
    validations:
      required: true

  - type: textarea
    id: bug_description
    attributes:
      label: Describe the bug
      placeholder: Describe what happened...
    validations:
      required: true

  - type: textarea
    id: repro_steps
    attributes:
      label: Steps to reproduce
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected behavior
      placeholder: Describe what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Debug log
      description: Drag and drop `veritas.debug.log` here.

  - type: checkboxes
    id: confirmations
    attributes:
      label: Before submitting
      options:
        - label: I attached `veritas.debug.log`
          required: true
        - label: I searched existing issues
          required: true
