on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write  # Required to create GitHub releases

    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-05-17
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "shared"
          save-if: "false"
      - run: cargo build --release

      - name: Format Release Name
        id: format_name
        shell: bash
        run: |
          RAW_TAG="${GITHUB_REF_NAME}"

          # Replace dashes between letters with spaces (e.g., global-beta)
          # Leave dashes between numbers (e.g., 0.1.3-0.2)
          FORMATTED_NAME=$(echo "$RAW_TAG" | \
            sed -E 's/([a-zA-Z])\-([a-zA-Z])/\1 \2/g' | \
            sed -E 's/([a-zA-Z])\-([0-9])/\1 \2/g' | \
            awk '{ for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) substr($i,2); print }')

          echo "Formatted release name: $FORMATTED_NAME"
          echo "release_name=$FORMATTED_NAME" >> "$GITHUB_OUTPUT"

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.format_name.outputs.release_name }}
          generate_release_notes: true
          target_commitish: cn-beta-nightly
          files: target/release/veritas.dll
          prerelease: true