name: Publish Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: windows-latest

    permissions:
      contents: write  # Required to create GitHub releases

    steps:
      - name: Set release name from tag
        id: format_name
        run: |
          # Extract tag name (without refs/tags/ prefix)
          TAG_NAME="${GITHUB_REF##*/}"
          echo "Release Name: $TAG_NAME"
          echo "release_name=$TAG_NAME" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v4
      
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-05-17
      
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: "shared"
          save-if: "false"

      - run: cargo build --release

      - name: Publish Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.format_name.outputs.release_name }}
          generate_release_notes: true
          target_commitish: ${{ github.sha }}
          files: target/release/veritas.dll
          make_latest: true